spring.application.name=costing-service
spring.datasource.url=jdbc:postgresql://localhost:5432/costing
spring.datasource.username=costing_service
spring.datasource.password=cs0101J
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
