spring.application.name=costing-service
spring.datasource.url=jdbc:postgresql://localhost:5432/costing
spring.datasource.username=postgres
spring.datasource.password=smroftapmi#0302
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
security.jwt.secret-key=cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
server.servlet.context-path=/api
# 12h in millisecond
security.jwt.expiration-time=43200000
#liquibase
spring.liquibase.change-log=classpath:liquibase/master.xml
spring.liquibase.test-rollback-on-update=true
aws.bucketName=costing-ui-angular
aws.region=ap-south-1
app.maxFileSizeBytes=5242880


#To check boolean existsByChildPart(Part childPart); Query--------------------------
# Show generated SQL queries in the console
#spring.jpa.show-sql=true

# Format the SQL queries for better readability
#spring.jpa.properties.hibernate.format_sql=true

# Log SQL parameter values (useful for debugging)
#logging.level.org.hibernate.type.descriptor.sql=TRACE
