spring.application.name=costing-service
spring.datasource.url=jdbc:postgresql://costing-service-db.ct0gcqo4gch9.ap-south-1.rds.amazonaws.com:5432/costing
spring.datasource.username=costing_service
spring.datasource.password=cs0101J
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#security.jwt.secret-key= place a secret key; an HMAC hash string of 256 bits
# 1h in millisecond
security.jwt.expiration-time=3600000

